rem This script will remove any Scheduled Tasks to do with Telemetry
schtasks /delete /F /TN "Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"
schtasks /delete /F /TN "Microsoft\Windows\Application Experience\ProgramDataUpdater"
schtasks /delete /F /TN "Microsoft\Windows\Autochk\Proxy"
schtasks /delete /F /TN "Microsoft\Windows\Customer Experience Improvement Program\Consolidator"
schtasks /delete /F /TN "Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask"
schtasks /delete /F /TN "Microsoft\Windows\Customer Experience Improvement Program\UsbCeip"
schtasks /delete /F /TN "Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector"
schtasks /delete /F /TN "Microsoft\Windows\PI\Sqm-Tasks"
schtasks /delete /F /TN "Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem"
schtasks /delete /F /TN "Microsoft\Windows\Windows Error Reporting\QueueReporting"
schtasks /delete /F /TN "Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"
schtasks /delete /F /TN "Microsoft\Windows\Application Experience\Aitagent"
schtasks /delete /F /TN "Microsoft\Windows\Application Experience\ProgramDataUpdater"
schtasks /delete /F /TN "Microsoft\Windows\Maintenance\Winsat"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\ActicateWIndowsSearch"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\ConfigureInternetTimeService"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\DispatchRecoveryTasks"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\Ehdrminit
schtasks /delete /F /TN "Microsoft\Windows\Media Center\InstallPlayReady"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\McUpdate"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\MediaCenterRecoveryTask"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\ObjectStoreRecoveryTask"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\OcurActivate"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\OcurDiscovery"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\PbdaDiscovery">nul 2>&1
schtasks /delete /F /TN "Microsoft\Windows\Media Center\PbdaDiscoveryw1"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\PbdaDiscoveryw2"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\PvvrRecoveryTask"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\PvrScheduleTask"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\RegisterSearch"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\ReindexSearchRoot"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\SqlliteRecoveryTask"
schtasks /delete /F /TN "Microsoft\Windows\Media Center\UpdateRecordPath"